version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Infinity@1
      MYSQL_DATABASE: rec_2024
      MYSQL_USER: vedant
      MYSQL_PASSWORD: Infinity@1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/vedant
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge