version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Infinity%401
      MYSQL_DATABASE: rec_2024
      MYSQL_USER: vedant
      MYSQL_PASSWORD: Infinity%401
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - 3000
    environment:
      DATABASE_URL: mysql2://vedant:Infinity%401@db:3306/rec_2024
    networks:
      - mynetwork

  web-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - 3000
    environment:
      DATABASE_URL: mysql2://vedant:Infinity%401@db:3306/rec_2024
    networks:
      - mynetwork

  web-3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    expose:
      - 3000
    environment:
      DATABASE_URL: mysql2://vedant:Infinity%401@db:3306/rec_2024
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx-1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_data:/etc/nginx/conf.d:ro
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  db_data:
  nginx_data:

networks:
  mynetwork:
    driver: bridge